Bird/sample
dsp-work/sound_utils pull request #8
Opened 2021-12-03 05:28 UTC by deffeather

CMake setup completed.

2021-12-03 08:54 UTC, chatblanc-ciel requested changes

2021-12-03 08:54 UTC, chatblanc-ciel commented on .github/workflows/cmake.yml
> +          apt-get -y install gnuplot
ここのgnuplotはまだ必要ないけど入れますか?

2021-12-03 08:54 UTC, chatblanc-ciel commented on CMakeLists.txt
> +    target_link_libraries(sound_utils INTERFACE reader)
ここプロジェクトネームに変えてない

2021-12-03 08:54 UTC, chatblanc-ciel commented on CMakeLists.txt
> +endif()
ここもプロジェクトネーム

2021-12-03 08:54 UTC, chatblanc-ciel commented on develop_main.cpp
> +}
いらない

2021-12-03 08:54 UTC, chatblanc-ciel commented on include/reader.hpp
> +#endif /* READER_HPP_ */
workflowだけならだけに限定したほうが〇

2021-12-03 08:54 UTC, chatblanc-ciel commented on sound_utils.code-workspace
> +	},
ここ最新では追加あったはず

2021-12-03 08:54 UTC, chatblanc-ciel commented on sound_utils.code-workspace
> +			"-DDEVELOP_EXECUTABLE_DIGITAL_FILTERS=ON"
直ってない

2021-12-03 08:54 UTC, chatblanc-ciel commented on test/reader/CMakeLists.txt
> +    )
まだテストないのでは？

2021-12-03 08:59 UTC, deffeather commented on .github/workflows/cmake.yml
> +          apt-get -y install gnuplot
今後使うことも考えて、残しておいてはいかがでしょう

2021-12-03 09:01 UTC, chatblanc-ciel commented on .github/workflows/cmake.yml
> +          apt-get -y install gnuplot
ok

2021-12-03 09:20 UTC, deffeather commented on CMakeLists.txt
> +    target_link_libraries(sound_utils INTERFACE reader)
修正完了

2021-12-03 09:20 UTC, deffeather commented on CMakeLists.txt
> +endif()
修正完了

2021-12-03 09:21 UTC, deffeather commented on develop_main.cpp
> +}
消した

2021-12-03 09:33 UTC, deffeather commented on sound_utils.code-workspace
> +			"-DDEVELOP_EXECUTABLE_DIGITAL_FILTERS=ON"
${PROJECT_NAME}に変更

2021-12-03 13:11 UTC, chatblanc-ciel requested changes
- `./DS_Store`が不要。できれば`.gitignore_grobal`に追記
- develop_mainが残ってる？(rebase必要かも)

2021-12-04 09:24 UTC, chatblanc-ciel requested changes

2021-12-04 09:24 UTC, chatblanc-ciel commented on sound_utils.code-workspace
> +			"-DDEVELOP_EXECUTABLE_${PROJECT_NAME}=ON"
ここで`${}`は使えません
Cmake_List内のみ

2021-12-04 09:24 UTC, chatblanc-ciel commented on CMakeLists.txt
> +project(digital_filters CXX)
ここも変わってない

2021-12-04 09:24 UTC, chatblanc-ciel commented on CMakeLists.txt
> +    target_link_libraries(${PROJECT_NAME} INTERFACE reader)
まだない

2021-12-04 09:30 UTC, chatblanc-ciel approved these changes

2021-12-04 09:32 UTC, merged